version: "3.7"

services:
  flask_mini_cms:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: flask-mini-cms
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
    volumes:
      - ./db:/code/server/project/db
      - ./logs:/code/server/logs
      - ./media:/code/server/project/static/img/media
    ports:
      - 50550:5000