version: "3.7"

services:
  flask_mini_cms:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: flask-mini-cms
    restart: unless-stopped
    volumes:
      - ./server/project/db:/code/server/project/db
    ports:
      - 50550:5000